AWSTemplateFormatVersion: "2010-09-09"
Description: Template for the CodePipeline resources

Parameters:

  ArtifactBucketName:
    Type: String
    Description: Where this pipeline should retrieve artifacts.
  WebsiteBucketName:
    Type: String
    Description: Where this pipeline should retrieve artifacts.

Resources:

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
                Effect: Allow
                Resource: '*'
              - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                  - s3:ListBucket,
                  - s3:DeleteObject,
                  - s3:GetBucketLocation,
                  - s3:PutBucketWebsite
                Resource: !Sub 'arn:aws:s3:::${WebsiteBucketName}'
                Effect: Allow
              - Action:
                  - cloudfront:*
                Resource: '*'
                Effect: Allow
              - Action:
                - s3:PutObject
                - s3:GetObject
                - s3:GetObjectVersion
                Effect: Allow
                Resource: !Sub 'arn:aws:s3:::*/*'

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
            - cloudformation.amazonaws.com
          Sid: 1
      Policies:
      - PolicyName: WorkerCodePipelineRolePolicy
        PolicyDocument:
          Statement:
            - Action:
                - iam:PassRole
              Resource: '*'
              Effect: Allow
            - Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:GetBucketVersioning
                - s3:PutObject
                - s3:ListBucket,
                - s3:DeleteObject,
                - s3:GetBucketLocation,
                - s3:PutBucketWebsite
              Resource: '*'
              Effect: Allow
            - Action:
                - s3:PutObject
              Resource: !Sub 'arn:aws:s3:::${ArtifactBucketName}/*'
              Effect: Allow
            - Action:
                - iam:*
              Resource: '*'
              Effect: Allow
            - Action:
                - codedeploy:CreateDeployment
                - codedeploy:GetApplication
                - codedeploy:GetApplicationRevision
                - codedeploy:GetDeployment
                - codedeploy:GetDeploymentConfig
                - codedeploy:RegisterApplicationRevision
              Resource: '*'
              Effect: Allow
            - Action:
                - cloudformation:CreateStack
                - cloudformation:DeleteStack
                - cloudformation:DescribeStacks
                - cloudformation:UpdateStack
                - cloudformation:CreateChangeSet
                - cloudformation:DeleteChangeSet
                - cloudformation:DescribeChangeSet
                - cloudformation:ExecuteChangeSet
                - cloudformation:SetStackPolicy
                - cloudformation:ValidateTemplate
              Resource: '*'
              Effect: Allow
            - Action:
                - lambda:AddPermission
                - lambda:CreateEventSourceMapping
                - lambda:CreateFunction
                - lambda:DeleteEventSourceMapping
                - lambda:DeleteFunction
                - lambda:GetEventSourceMapping
                - lambda:GetFunctionConfiguration
                - lambda:InvokeFunction
                - lambda:ListFunctions
                - lambda:RemovePermission
                - lambda:UpdateFunctionCode
                - lambda:UpdateFunctionConfiguration
              Resource: '*'
              Effect: Allow
            - Action:
                - codebuild:BatchGetBuilds
                - codebuild:StartBuild
              Resource: '*'
              Effect: Allow


Outputs:

  CodePipelineServiceRoleArn:
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CodePipelineServiceRoleArn

  CodeBuildServiceRoleArn:
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CodeBuildServiceRoleArn
